version: '2.1'
services:
    dremio:
        image: dremio/dremio-oss
        ports:
            - 9047:9047
            - 31010:31010
            - 45678:45678
        volumes:
            - ./dremio/conf:/opt/dremio/conf
            - ./dremio/data/db:/opt/dremio/data/db

    elasticsearch:
        image: elasticsearch:6.8.0
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
